import LeanAideCore
import Mathlib
set_option linter.style.commandStart false
set_option linter.style.longLine false

-- #leanaide_connect "http://drongo:8042"

/-
### Theorem:


### Proof:


-/

-- ### JSON Structured Proof

--def := json%{}


-- ## LeanCode generated by LeanAide

def eg₀ : List Nat := do
  let l ←  [[1, 2], [3, 4]]
  let x ← l
  let z ← l
  return x

#eval eg₀
